Add --keep-original-year flag to allow stale years to be unchanged
Lucas-C/pre-commit-hooks pull request #78
Opened 2023-08-01 14:37 UTC by yiftachkarkason

This allows use cases where the license needs to contain the creation time of the file (i.e. [like in Chromium](https://source.chromium.org/chromium/chromium/src/+/main:base/files/file_enumerator.cc)).

2023-08-01 22:11 UTC, Lucas-C commented
Hi @yiftachkarkason!

Thank you for suggesting a new feature 😊

I wonder if this really neeeds a new optional parameter...
Shouldn't this be the default behaviour?
I'd be tempted to get rid of `match_years_strictly` in `insert_license.py` and just consider it always true.
What do you think?

Also, please run `black pre_commit_hooks/insert_license.py` in order for this file to be correctly formatted,
otherwise the GitHub Actions pipeline will fail.

2023-08-02 12:48 UTC, yiftachkarkason commented
Hey @Lucas-C ! My PR actually uses `match_years_strictly=False` to allow past years to remain in the license, so I wouldn't remove `match_years_strictly` because it allows this flexibility

2023-08-03 17:59 UTC, Lucas-C commented
> My PR actually uses `match_years_strictly=False` to allow past years to remain in the license, so I wouldn't remove `match_years_strictly` because it allows this flexibility

Alright. I made a few suggestions.
If you're fine with them, I'll be happy to merge this new feature!

2023-08-03 18:44 UTC, yiftachkarkason commented
> > My PR actually uses `match_years_strictly=False` to allow past years to remain in the license, so I wouldn't remove `match_years_strictly` because it allows this flexibility
> 
> Alright. I made a few suggestions. If you're fine with them, I'll be happy to merge this new feature!

Great!
Where can I find the suggestions?

2023-08-03 19:46 UTC, Lucas-C requested changes

2023-08-03 19:46 UTC, Lucas-C commented
> Where can I find the suggestions?

Sorry, I forgot to publish my review 😅
You should see them now

2023-08-03 22:18 UTC, yiftachkarkason commented on README.md
> +You can also use `--keep-original-year` to allow stale years to be unchanged. Using both `--keep-original-year`
```suggestion
You can also use `--allow-past-years` to allow stale years to be unchanged. Using both `--allow-past-years` 
```

2023-08-03 22:19 UTC, yiftachkarkason commented
> > Where can I find the suggestions?
> 
> Sorry, I forgot to publish my review 😅 You should see them now

Cool suggestions! Applied them 😄

2023-08-04 09:12 UTC, Lucas-C commented on README.md
> +and `--use-current-year` issues a year range as described above.
```suggestion
You can also use `--allow-past-years` to allow stale years to be unchanged.
Using both `--allow-past-years` and `--use-current-year` issues a year
range as described above.
```

2023-08-04 09:13 UTC, merged

2023-08-04 09:13 UTC, Lucas-C commented
Merged! Thank you for your contribution @yiftachkarkason 👍

2023-08-04 09:16 UTC, Lucas-C commented
This has been released in https://github.com/Lucas-C/pre-commit-hooks/releases/tag/v1.5.3